version: '3.7'
services:
  postgres:
    image: postgres:12.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: pg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
  redis:
    image: redis:6.0-alpine
    ports:
      - '6379:6379'
  backend:
    depends_on:
      - postgres
      - redis
    build:
      context: './packages/server'
    volumes:
      - './packages/server:/exec'
    ports:
      - '3000:3000'
  frontend:
    depends_on:
      - backend
    environment:
      VUE_APP_GRAPHQL_HTTP: 'http://localhost:3000/graphql'
      VUE_APP_GRAPHQL_WS: 'ws://localhost:3000/graphql'
    build:
      context: './packages/frontend'
    volumes:
      - './packages/frontend:/exec'
    ports:
      - '8080:8080'
volumes:
  pg_data:
